console.log('data file ')
module.exports= ()=>console.log('function string')
module.exports= ()=>console.log('function string2')
module.exports= ()=>console.log('function string55')
console.log('code outside the function')